import 'package:flutter_forge/services/version_service.dart';
import 'package:flutter_test/flutter_test.dart';

/// Tests for Version Service (J24 S4: Flutter Version Runtime Info)
///
/// Task 9.2.4: Flutter Version Runtime Info (3.32)
void main() {
  group('Flutter Version Runtime Info (Task 9.2.4)', () {
    late VersionService versionService;

    setUp(() {
      versionService = VersionService();
    });

    group('Version Detection (J24 S4)', () {
      test('returns FlutterForge version', () {
        final info = versionService.getVersionInfo();

        expect(info.flutterForgeVersion, isNotEmpty);
        // Should be semantic version format
        expect(
          info.flutterForgeVersion,
          matches(RegExp(r'^\d+\.\d+\.\d+')),
        );
      });

      test('returns Flutter SDK version', () {
        final info = versionService.getVersionInfo();

        expect(info.flutterVersion, isNotEmpty);
      });

      test('returns Dart version', () {
        final info = versionService.getVersionInfo();

        expect(info.dartVersion, isNotEmpty);
      });

      test('returns engine ID when available', () {
        final info = versionService.getVersionInfo();

        // Engine ID may be null in tests but should exist in runtime
        expect(info, isA<VersionInfo>());
      });
    });

    group('Version-Aware Feature Flags (J24 S4)', () {
      test('checks if feature is available for current Flutter version', () {
        // @Preview is available in Flutter 3.32+
        final previewAvailable = versionService.isFeatureAvailable(
          feature: FlutterFeature.previewAnnotation,
        );

        expect(previewAvailable, isA<bool>());
      });

      test('returns tooltip for unavailable feature', () {
        final tooltip = versionService.getFeatureTooltip(
          feature: FlutterFeature.previewAnnotation,
          currentVersion: '3.30.0',
        );

        expect(tooltip, contains('3.32'));
        expect(tooltip, contains('required'));
      });

      test('returns null tooltip when feature is available', () {
        final tooltip = versionService.getFeatureTooltip(
          feature: FlutterFeature.previewAnnotation,
          currentVersion: '3.35.0',
        );

        expect(tooltip, isNull);
      });

      test('previewThemeBrightness requires Flutter 3.35+', () {
        expect(
          versionService
              .getMinimumVersion(FlutterFeature.previewThemeBrightness),
          equals('3.35.0'),
        );
      });

      test('previewLocale requires Flutter 3.35+', () {
        expect(
          versionService.getMinimumVersion(FlutterFeature.previewLocale),
          equals('3.35.0'),
        );
      });

      test('multiPreview requires Flutter 3.38+', () {
        expect(
          versionService.getMinimumVersion(FlutterFeature.multiPreview),
          equals('3.38.0'),
        );
      });
    });

    group('Version Comment Export (J24 S4)', () {
      test('generates version comment header', () {
        final comment = versionService.generateVersionComment(
          flutterForgeVersion: '1.1.0',
          minFlutterVersion: '3.32',
          minDartVersion: '3.10',
        );

        expect(comment, contains('Generated by FlutterForge v1.1.0'));
        expect(comment, contains('Flutter 3.32+'));
        expect(comment, contains('Dart 3.10+'));
      });

      test('formats version comment as Dart comment', () {
        final comment = versionService.generateVersionComment(
          flutterForgeVersion: '1.0.0',
        );

        expect(comment, startsWith('//'));
      });

      test('includes generation timestamp when requested', () {
        final comment = versionService.generateVersionComment(
          flutterForgeVersion: '1.1.0',
          includeTimestamp: true,
        );

        // Should have some date/time format
        expect(comment, matches(RegExp(r'\d{4}-\d{2}-\d{2}')));
      });
    });

    group('Engine ID for Debugging (J24 S4)', () {
      test('retrieves engine ID', () {
        final engineId = versionService.getEngineId();

        // Engine ID may be null in test environment
        // In multi-window setups, each window has unique ID
        expect(engineId, anyOf(isNull, isA<int>()));
      });

      test('formats engine ID for display', () {
        final display = versionService.formatEngineIdForDisplay(123);

        expect(display, contains('123'));
        expect(display, contains('Engine'));
      });

      test('handles null engine ID gracefully', () {
        final display = versionService.formatEngineIdForDisplay(null);

        expect(display, equals('Engine: N/A'));
      });
    });

    group('Version Comparison', () {
      test('compares semantic versions correctly', () {
        expect(
          versionService.isVersionAtLeast('3.32.0', '3.32.0'),
          isTrue,
        );
        expect(
          versionService.isVersionAtLeast('3.35.0', '3.32.0'),
          isTrue,
        );
        expect(
          versionService.isVersionAtLeast('3.30.0', '3.32.0'),
          isFalse,
        );
      });

      test('handles version with patch numbers', () {
        expect(
          versionService.isVersionAtLeast('3.32.1', '3.32.0'),
          isTrue,
        );
        expect(
          versionService.isVersionAtLeast('3.32.0', '3.32.1'),
          isFalse,
        );
      });

      test('handles version with pre-release tags', () {
        // 3.35.0-beta should be treated as less than 3.35.0
        expect(
          versionService.isVersionAtLeast('3.35.0-beta', '3.35.0'),
          isFalse,
        );
      });
    });
  });

  group('VersionInfo', () {
    test('creates VersionInfo with all fields', () {
      const info = VersionInfo(
        flutterForgeVersion: '1.1.0',
        flutterVersion: '3.35.0',
        dartVersion: '3.10.0',
        engineId: 123,
      );

      expect(info.flutterForgeVersion, equals('1.1.0'));
      expect(info.flutterVersion, equals('3.35.0'));
      expect(info.dartVersion, equals('3.10.0'));
      expect(info.engineId, equals(123));
    });

    test('creates VersionInfo with null engine ID', () {
      const info = VersionInfo(
        flutterForgeVersion: '1.0.0',
        flutterVersion: '3.32.0',
        dartVersion: '3.9.0',
      );

      expect(info.engineId, isNull);
    });

    test('toString provides readable format', () {
      const info = VersionInfo(
        flutterForgeVersion: '1.1.0',
        flutterVersion: '3.35.0',
        dartVersion: '3.10.0',
      );

      final string = info.toString();

      expect(string, contains('FlutterForge'));
      expect(string, contains('1.1.0'));
      expect(string, contains('Flutter'));
      expect(string, contains('Dart'));
    });
  });

  group('FlutterFeature', () {
    test('has all expected features', () {
      expect(
        FlutterFeature.values,
        contains(FlutterFeature.previewAnnotation),
      );
      expect(
        FlutterFeature.values,
        contains(FlutterFeature.previewThemeBrightness),
      );
      expect(FlutterFeature.values, contains(FlutterFeature.previewLocale));
      expect(FlutterFeature.values, contains(FlutterFeature.multiPreview));
      expect(FlutterFeature.values, contains(FlutterFeature.engineId));
    });
  });
}
